//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHDBAN
    {
        public string MAHDBAN { get; set; }
        public string MAHANG { get; set; }
        public int SOLUONGMUA { get; set; }
        public double DONGIA { get; set; }
        public double GIAMGIA { get; set; }
        public double THANHTIEN { get; set; }
    
        public virtual HANG HANG { get; set; }
        public virtual HDBAN HDBAN { get; set; }
    }
}
