//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANG()
        {
            this.CHITIETHDBANs = new HashSet<CHITIETHDBAN>();
        }
    
        public string MAHANG { get; set; }
        public string TENHANG { get; set; }
        public int SOLUONG { get; set; }
        public string MALOAIHANG { get; set; }
        public double DONGIANHAP { get; set; }
        public double DONGIABAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHDBAN> CHITIETHDBANs { get; set; }
        public virtual LOAIHANG LOAIHANG { get; set; }
    }
}
