//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HDBANs = new HashSet<HDBAN>();
        }
    
        public string MANHANVIEN { get; set; }
        public string TENNHANVIEN { get; set; }
        public string GIOITINH { get; set; }
        public string DIACHI_NV { get; set; }
        public string DIENTHOAI_NV { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDBAN> HDBANs { get; set; }
    }
}
