#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_CUAHANGTIENLOI")]
	public partial class QLCuaHangTienLoiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHITIETHDBAN(CHITIETHDBAN instance);
    partial void UpdateCHITIETHDBAN(CHITIETHDBAN instance);
    partial void DeleteCHITIETHDBAN(CHITIETHDBAN instance);
    partial void InsertHANG(HANG instance);
    partial void UpdateHANG(HANG instance);
    partial void DeleteHANG(HANG instance);
    partial void InsertHDBAN(HDBAN instance);
    partial void UpdateHDBAN(HDBAN instance);
    partial void DeleteHDBAN(HDBAN instance);
    partial void InsertKHACH(KHACH instance);
    partial void UpdateKHACH(KHACH instance);
    partial void DeleteKHACH(KHACH instance);
    partial void InsertLOAIHANG(LOAIHANG instance);
    partial void UpdateLOAIHANG(LOAIHANG instance);
    partial void DeleteLOAIHANG(LOAIHANG instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    #endregion
		
		public QLCuaHangTienLoiDataContext() : 
				base(global::BLL_DAL.Properties.Settings.Default.QL_CUAHANGTIENLOIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLCuaHangTienLoiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCuaHangTienLoiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCuaHangTienLoiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCuaHangTienLoiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHITIETHDBAN> CHITIETHDBANs
		{
			get
			{
				return this.GetTable<CHITIETHDBAN>();
			}
		}
		
		public System.Data.Linq.Table<HANG> HANGs
		{
			get
			{
				return this.GetTable<HANG>();
			}
		}
		
		public System.Data.Linq.Table<HDBAN> HDBANs
		{
			get
			{
				return this.GetTable<HDBAN>();
			}
		}
		
		public System.Data.Linq.Table<KHACH> KHACHes
		{
			get
			{
				return this.GetTable<KHACH>();
			}
		}
		
		public System.Data.Linq.Table<LOAIHANG> LOAIHANGs
		{
			get
			{
				return this.GetTable<LOAIHANG>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETHDBAN")]
	public partial class CHITIETHDBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHDBAN;
		
		private string _MAHANG;
		
		private int _SOLUONGMUA;
		
		private double _DONGIA;
		
		private double _GIAMGIA;
		
		private double _THANHTIEN;
		
		private EntityRef<HANG> _HANG;
		
		private EntityRef<HDBAN> _HDBAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDBANChanging(string value);
    partial void OnMAHDBANChanged();
    partial void OnMAHANGChanging(string value);
    partial void OnMAHANGChanged();
    partial void OnSOLUONGMUAChanging(int value);
    partial void OnSOLUONGMUAChanged();
    partial void OnDONGIAChanging(double value);
    partial void OnDONGIAChanged();
    partial void OnGIAMGIAChanging(double value);
    partial void OnGIAMGIAChanged();
    partial void OnTHANHTIENChanging(double value);
    partial void OnTHANHTIENChanged();
    #endregion
		
		public CHITIETHDBAN()
		{
			this._HANG = default(EntityRef<HANG>);
			this._HDBAN = default(EntityRef<HDBAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHDBAN", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHDBAN
		{
			get
			{
				return this._MAHDBAN;
			}
			set
			{
				if ((this._MAHDBAN != value))
				{
					if (this._HDBAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHDBANChanging(value);
					this.SendPropertyChanging();
					this._MAHDBAN = value;
					this.SendPropertyChanged("MAHDBAN");
					this.OnMAHDBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHANG", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHANG
		{
			get
			{
				return this._MAHANG;
			}
			set
			{
				if ((this._MAHANG != value))
				{
					if (this._HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHANGChanging(value);
					this.SendPropertyChanging();
					this._MAHANG = value;
					this.SendPropertyChanged("MAHANG");
					this.OnMAHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONGMUA", DbType="Int NOT NULL")]
		public int SOLUONGMUA
		{
			get
			{
				return this._SOLUONGMUA;
			}
			set
			{
				if ((this._SOLUONGMUA != value))
				{
					this.OnSOLUONGMUAChanging(value);
					this.SendPropertyChanging();
					this._SOLUONGMUA = value;
					this.SendPropertyChanged("SOLUONGMUA");
					this.OnSOLUONGMUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Float NOT NULL")]
		public double DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIAMGIA", DbType="Float NOT NULL")]
		public double GIAMGIA
		{
			get
			{
				return this._GIAMGIA;
			}
			set
			{
				if ((this._GIAMGIA != value))
				{
					this.OnGIAMGIAChanging(value);
					this.SendPropertyChanging();
					this._GIAMGIA = value;
					this.SendPropertyChanged("GIAMGIA");
					this.OnGIAMGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="Float NOT NULL")]
		public double THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this.OnTHANHTIENChanging(value);
					this.SendPropertyChanging();
					this._THANHTIEN = value;
					this.SendPropertyChanged("THANHTIEN");
					this.OnTHANHTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANG_CHITIETHDBAN", Storage="_HANG", ThisKey="MAHANG", OtherKey="MAHANG", IsForeignKey=true)]
		public HANG HANG
		{
			get
			{
				return this._HANG.Entity;
			}
			set
			{
				HANG previousValue = this._HANG.Entity;
				if (((previousValue != value) 
							|| (this._HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HANG.Entity = null;
						previousValue.CHITIETHDBANs.Remove(this);
					}
					this._HANG.Entity = value;
					if ((value != null))
					{
						value.CHITIETHDBANs.Add(this);
						this._MAHANG = value.MAHANG;
					}
					else
					{
						this._MAHANG = default(string);
					}
					this.SendPropertyChanged("HANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HDBAN_CHITIETHDBAN", Storage="_HDBAN", ThisKey="MAHDBAN", OtherKey="MAHDBAN", IsForeignKey=true)]
		public HDBAN HDBAN
		{
			get
			{
				return this._HDBAN.Entity;
			}
			set
			{
				HDBAN previousValue = this._HDBAN.Entity;
				if (((previousValue != value) 
							|| (this._HDBAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HDBAN.Entity = null;
						previousValue.CHITIETHDBANs.Remove(this);
					}
					this._HDBAN.Entity = value;
					if ((value != null))
					{
						value.CHITIETHDBANs.Add(this);
						this._MAHDBAN = value.MAHDBAN;
					}
					else
					{
						this._MAHDBAN = default(string);
					}
					this.SendPropertyChanged("HDBAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HANG")]
	public partial class HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHANG;
		
		private string _TENHANG;
		
		private int _SOLUONG;
		
		private string _MALOAIHANG;
		
		private double _DONGIANHAP;
		
		private double _DONGIABAN;
		
		private EntitySet<CHITIETHDBAN> _CHITIETHDBANs;
		
		private EntityRef<LOAIHANG> _LOAIHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHANGChanging(string value);
    partial void OnMAHANGChanged();
    partial void OnTENHANGChanging(string value);
    partial void OnTENHANGChanged();
    partial void OnSOLUONGChanging(int value);
    partial void OnSOLUONGChanged();
    partial void OnMALOAIHANGChanging(string value);
    partial void OnMALOAIHANGChanged();
    partial void OnDONGIANHAPChanging(double value);
    partial void OnDONGIANHAPChanged();
    partial void OnDONGIABANChanging(double value);
    partial void OnDONGIABANChanged();
    #endregion
		
		public HANG()
		{
			this._CHITIETHDBANs = new EntitySet<CHITIETHDBAN>(new Action<CHITIETHDBAN>(this.attach_CHITIETHDBANs), new Action<CHITIETHDBAN>(this.detach_CHITIETHDBANs));
			this._LOAIHANG = default(EntityRef<LOAIHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHANG", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHANG
		{
			get
			{
				return this._MAHANG;
			}
			set
			{
				if ((this._MAHANG != value))
				{
					this.OnMAHANGChanging(value);
					this.SendPropertyChanging();
					this._MAHANG = value;
					this.SendPropertyChanged("MAHANG");
					this.OnMAHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHANG", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENHANG
		{
			get
			{
				return this._TENHANG;
			}
			set
			{
				if ((this._TENHANG != value))
				{
					this.OnTENHANGChanging(value);
					this.SendPropertyChanging();
					this._TENHANG = value;
					this.SendPropertyChanged("TENHANG");
					this.OnTENHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int NOT NULL")]
		public int SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAIHANG", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MALOAIHANG
		{
			get
			{
				return this._MALOAIHANG;
			}
			set
			{
				if ((this._MALOAIHANG != value))
				{
					if (this._LOAIHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIHANGChanging(value);
					this.SendPropertyChanging();
					this._MALOAIHANG = value;
					this.SendPropertyChanged("MALOAIHANG");
					this.OnMALOAIHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIANHAP", DbType="Float NOT NULL")]
		public double DONGIANHAP
		{
			get
			{
				return this._DONGIANHAP;
			}
			set
			{
				if ((this._DONGIANHAP != value))
				{
					this.OnDONGIANHAPChanging(value);
					this.SendPropertyChanging();
					this._DONGIANHAP = value;
					this.SendPropertyChanged("DONGIANHAP");
					this.OnDONGIANHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIABAN", DbType="Float NOT NULL")]
		public double DONGIABAN
		{
			get
			{
				return this._DONGIABAN;
			}
			set
			{
				if ((this._DONGIABAN != value))
				{
					this.OnDONGIABANChanging(value);
					this.SendPropertyChanging();
					this._DONGIABAN = value;
					this.SendPropertyChanged("DONGIABAN");
					this.OnDONGIABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANG_CHITIETHDBAN", Storage="_CHITIETHDBANs", ThisKey="MAHANG", OtherKey="MAHANG")]
		public EntitySet<CHITIETHDBAN> CHITIETHDBANs
		{
			get
			{
				return this._CHITIETHDBANs;
			}
			set
			{
				this._CHITIETHDBANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIHANG_HANG", Storage="_LOAIHANG", ThisKey="MALOAIHANG", OtherKey="MALOAIHANG", IsForeignKey=true)]
		public LOAIHANG LOAIHANG
		{
			get
			{
				return this._LOAIHANG.Entity;
			}
			set
			{
				LOAIHANG previousValue = this._LOAIHANG.Entity;
				if (((previousValue != value) 
							|| (this._LOAIHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIHANG.Entity = null;
						previousValue.HANGs.Remove(this);
					}
					this._LOAIHANG.Entity = value;
					if ((value != null))
					{
						value.HANGs.Add(this);
						this._MALOAIHANG = value.MALOAIHANG;
					}
					else
					{
						this._MALOAIHANG = default(string);
					}
					this.SendPropertyChanged("LOAIHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHDBANs(CHITIETHDBAN entity)
		{
			this.SendPropertyChanging();
			entity.HANG = this;
		}
		
		private void detach_CHITIETHDBANs(CHITIETHDBAN entity)
		{
			this.SendPropertyChanging();
			entity.HANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HDBAN")]
	public partial class HDBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHDBAN;
		
		private string _MANHANVIEN;
		
		private System.DateTime _NGAYBAN;
		
		private string _MAKHACH;
		
		private double _TONGTIEN;
		
		private EntitySet<CHITIETHDBAN> _CHITIETHDBANs;
		
		private EntityRef<KHACH> _KHACH;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDBANChanging(string value);
    partial void OnMAHDBANChanged();
    partial void OnMANHANVIENChanging(string value);
    partial void OnMANHANVIENChanged();
    partial void OnNGAYBANChanging(System.DateTime value);
    partial void OnNGAYBANChanged();
    partial void OnMAKHACHChanging(string value);
    partial void OnMAKHACHChanged();
    partial void OnTONGTIENChanging(double value);
    partial void OnTONGTIENChanged();
    #endregion
		
		public HDBAN()
		{
			this._CHITIETHDBANs = new EntitySet<CHITIETHDBAN>(new Action<CHITIETHDBAN>(this.attach_CHITIETHDBANs), new Action<CHITIETHDBAN>(this.detach_CHITIETHDBANs));
			this._KHACH = default(EntityRef<KHACH>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHDBAN", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHDBAN
		{
			get
			{
				return this._MAHDBAN;
			}
			set
			{
				if ((this._MAHDBAN != value))
				{
					this.OnMAHDBANChanging(value);
					this.SendPropertyChanging();
					this._MAHDBAN = value;
					this.SendPropertyChanged("MAHDBAN");
					this.OnMAHDBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANVIEN", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MANHANVIEN
		{
			get
			{
				return this._MANHANVIEN;
			}
			set
			{
				if ((this._MANHANVIEN != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHANVIENChanging(value);
					this.SendPropertyChanging();
					this._MANHANVIEN = value;
					this.SendPropertyChanged("MANHANVIEN");
					this.OnMANHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYBAN", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYBAN
		{
			get
			{
				return this._NGAYBAN;
			}
			set
			{
				if ((this._NGAYBAN != value))
				{
					this.OnNGAYBANChanging(value);
					this.SendPropertyChanging();
					this._NGAYBAN = value;
					this.SendPropertyChanged("NGAYBAN");
					this.OnNGAYBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHACH", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MAKHACH
		{
			get
			{
				return this._MAKHACH;
			}
			set
			{
				if ((this._MAKHACH != value))
				{
					if (this._KHACH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHACHChanging(value);
					this.SendPropertyChanging();
					this._MAKHACH = value;
					this.SendPropertyChanged("MAKHACH");
					this.OnMAKHACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Float NOT NULL")]
		public double TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HDBAN_CHITIETHDBAN", Storage="_CHITIETHDBANs", ThisKey="MAHDBAN", OtherKey="MAHDBAN")]
		public EntitySet<CHITIETHDBAN> CHITIETHDBANs
		{
			get
			{
				return this._CHITIETHDBANs;
			}
			set
			{
				this._CHITIETHDBANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HDBAN", Storage="_KHACH", ThisKey="MAKHACH", OtherKey="MAKHACH", IsForeignKey=true)]
		public KHACH KHACH
		{
			get
			{
				return this._KHACH.Entity;
			}
			set
			{
				KHACH previousValue = this._KHACH.Entity;
				if (((previousValue != value) 
							|| (this._KHACH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH.Entity = null;
						previousValue.HDBANs.Remove(this);
					}
					this._KHACH.Entity = value;
					if ((value != null))
					{
						value.HDBANs.Add(this);
						this._MAKHACH = value.MAKHACH;
					}
					else
					{
						this._MAKHACH = default(string);
					}
					this.SendPropertyChanged("KHACH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HDBAN", Storage="_NHANVIEN", ThisKey="MANHANVIEN", OtherKey="MANHANVIEN", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.HDBANs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.HDBANs.Add(this);
						this._MANHANVIEN = value.MANHANVIEN;
					}
					else
					{
						this._MANHANVIEN = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHDBANs(CHITIETHDBAN entity)
		{
			this.SendPropertyChanging();
			entity.HDBAN = this;
		}
		
		private void detach_CHITIETHDBANs(CHITIETHDBAN entity)
		{
			this.SendPropertyChanging();
			entity.HDBAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACH")]
	public partial class KHACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKHACH;
		
		private string _TENKHACH;
		
		private string _DIACHI_KH;
		
		private string _DIENTHOAI_KH;
		
		private EntitySet<HDBAN> _HDBANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHACHChanging(string value);
    partial void OnMAKHACHChanged();
    partial void OnTENKHACHChanging(string value);
    partial void OnTENKHACHChanged();
    partial void OnDIACHI_KHChanging(string value);
    partial void OnDIACHI_KHChanged();
    partial void OnDIENTHOAI_KHChanging(string value);
    partial void OnDIENTHOAI_KHChanged();
    #endregion
		
		public KHACH()
		{
			this._HDBANs = new EntitySet<HDBAN>(new Action<HDBAN>(this.attach_HDBANs), new Action<HDBAN>(this.detach_HDBANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHACH", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKHACH
		{
			get
			{
				return this._MAKHACH;
			}
			set
			{
				if ((this._MAKHACH != value))
				{
					this.OnMAKHACHChanging(value);
					this.SendPropertyChanging();
					this._MAKHACH = value;
					this.SendPropertyChanged("MAKHACH");
					this.OnMAKHACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKHACH", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string TENKHACH
		{
			get
			{
				return this._TENKHACH;
			}
			set
			{
				if ((this._TENKHACH != value))
				{
					this.OnTENKHACHChanging(value);
					this.SendPropertyChanging();
					this._TENKHACH = value;
					this.SendPropertyChanged("TENKHACH");
					this.OnTENKHACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI_KH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DIACHI_KH
		{
			get
			{
				return this._DIACHI_KH;
			}
			set
			{
				if ((this._DIACHI_KH != value))
				{
					this.OnDIACHI_KHChanging(value);
					this.SendPropertyChanging();
					this._DIACHI_KH = value;
					this.SendPropertyChanged("DIACHI_KH");
					this.OnDIACHI_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI_KH", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DIENTHOAI_KH
		{
			get
			{
				return this._DIENTHOAI_KH;
			}
			set
			{
				if ((this._DIENTHOAI_KH != value))
				{
					this.OnDIENTHOAI_KHChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI_KH = value;
					this.SendPropertyChanged("DIENTHOAI_KH");
					this.OnDIENTHOAI_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HDBAN", Storage="_HDBANs", ThisKey="MAKHACH", OtherKey="MAKHACH")]
		public EntitySet<HDBAN> HDBANs
		{
			get
			{
				return this._HDBANs;
			}
			set
			{
				this._HDBANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HDBANs(HDBAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACH = this;
		}
		
		private void detach_HDBANs(HDBAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIHANG")]
	public partial class LOAIHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOAIHANG;
		
		private string _TENLOAIHANG;
		
		private EntitySet<HANG> _HANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIHANGChanging(string value);
    partial void OnMALOAIHANGChanged();
    partial void OnTENLOAIHANGChanging(string value);
    partial void OnTENLOAIHANGChanged();
    #endregion
		
		public LOAIHANG()
		{
			this._HANGs = new EntitySet<HANG>(new Action<HANG>(this.attach_HANGs), new Action<HANG>(this.detach_HANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAIHANG", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAIHANG
		{
			get
			{
				return this._MALOAIHANG;
			}
			set
			{
				if ((this._MALOAIHANG != value))
				{
					this.OnMALOAIHANGChanging(value);
					this.SendPropertyChanging();
					this._MALOAIHANG = value;
					this.SendPropertyChanged("MALOAIHANG");
					this.OnMALOAIHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAIHANG", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string TENLOAIHANG
		{
			get
			{
				return this._TENLOAIHANG;
			}
			set
			{
				if ((this._TENLOAIHANG != value))
				{
					this.OnTENLOAIHANGChanging(value);
					this.SendPropertyChanging();
					this._TENLOAIHANG = value;
					this.SendPropertyChanged("TENLOAIHANG");
					this.OnTENLOAIHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIHANG_HANG", Storage="_HANGs", ThisKey="MALOAIHANG", OtherKey="MALOAIHANG")]
		public EntitySet<HANG> HANGs
		{
			get
			{
				return this._HANGs;
			}
			set
			{
				this._HANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HANGs(HANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAIHANG = this;
		}
		
		private void detach_HANGs(HANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAIHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANHANVIEN;
		
		private string _TENNHANVIEN;
		
		private string _GIOITINH;
		
		private string _DIACHI_NV;
		
		private string _DIENTHOAI_NV;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private EntitySet<HDBAN> _HDBANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHANVIENChanging(string value);
    partial void OnMANHANVIENChanged();
    partial void OnTENNHANVIENChanging(string value);
    partial void OnTENNHANVIENChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnDIACHI_NVChanging(string value);
    partial void OnDIACHI_NVChanged();
    partial void OnDIENTHOAI_NVChanging(string value);
    partial void OnDIENTHOAI_NVChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._HDBANs = new EntitySet<HDBAN>(new Action<HDBAN>(this.attach_HDBANs), new Action<HDBAN>(this.detach_HDBANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANVIEN", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANHANVIEN
		{
			get
			{
				return this._MANHANVIEN;
			}
			set
			{
				if ((this._MANHANVIEN != value))
				{
					this.OnMANHANVIENChanging(value);
					this.SendPropertyChanging();
					this._MANHANVIEN = value;
					this.SendPropertyChanged("MANHANVIEN");
					this.OnMANHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNHANVIEN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENNHANVIEN
		{
			get
			{
				return this._TENNHANVIEN;
			}
			set
			{
				if ((this._TENNHANVIEN != value))
				{
					this.OnTENNHANVIENChanging(value);
					this.SendPropertyChanging();
					this._TENNHANVIEN = value;
					this.SendPropertyChanged("TENNHANVIEN");
					this.OnTENNHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI_NV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DIACHI_NV
		{
			get
			{
				return this._DIACHI_NV;
			}
			set
			{
				if ((this._DIACHI_NV != value))
				{
					this.OnDIACHI_NVChanging(value);
					this.SendPropertyChanging();
					this._DIACHI_NV = value;
					this.SendPropertyChanged("DIACHI_NV");
					this.OnDIACHI_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI_NV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DIENTHOAI_NV
		{
			get
			{
				return this._DIENTHOAI_NV;
			}
			set
			{
				if ((this._DIENTHOAI_NV != value))
				{
					this.OnDIENTHOAI_NVChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI_NV = value;
					this.SendPropertyChanged("DIENTHOAI_NV");
					this.OnDIENTHOAI_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HDBAN", Storage="_HDBANs", ThisKey="MANHANVIEN", OtherKey="MANHANVIEN")]
		public EntitySet<HDBAN> HDBANs
		{
			get
			{
				return this._HDBANs;
			}
			set
			{
				this._HDBANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HDBANs(HDBAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_HDBANs(HDBAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
}
#pragma warning restore 1591
