//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CuaHangTienLoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETNHAPHANG
    {
        public string ID { get; set; }
        public string MANHAPHANG { get; set; }
        public string MASP { get; set; }
        public double GIA { get; set; }
        public int SOLUONG { get; set; }
        public double TONG { get; set; }
    
        public virtual NHAPHANG NHAPHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
