//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CuaHangTienLoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH
    {
        public KHACH()
        {
            this.HDBANs = new HashSet<HDBAN>();
        }
    
        public string MAKHACH { get; set; }
        public string TENKHACH { get; set; }
        public string DIACHI_KH { get; set; }
        public string DIENTHOAI_KH { get; set; }
    
        public virtual ICollection<HDBAN> HDBANs { get; set; }
    }
}
