//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CuaHangTienLoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.HDBANs = new HashSet<HDBAN>();
            this.NHAPHANGs = new HashSet<NHAPHANG>();
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public string MANHANVIEN { get; set; }
        public string TENNHANVIEN { get; set; }
        public string MACHUCVU { get; set; }
        public string GIOITINH { get; set; }
        public string DIACHI_NV { get; set; }
        public string DIENTHOAI_NV { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual ICollection<HDBAN> HDBANs { get; set; }
        public virtual ICollection<NHAPHANG> NHAPHANGs { get; set; }
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
