//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_CuaHangTienLoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPHANG
    {
        public NHAPHANG()
        {
            this.CHITIETNHAPHANGs = new HashSet<CHITIETNHAPHANG>();
        }
    
        public string MANHAPHANG { get; set; }
        public System.DateTime NGAYTAO { get; set; }
        public double TONGTIEN { get; set; }
        public string MANHANVIEN { get; set; }
    
        public virtual ICollection<CHITIETNHAPHANG> CHITIETNHAPHANGs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
